Algoritmo "EX02"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/10/2021
Var
// Seção de Declarações das variáveis 
nome: caractere

Inicio
escreval("Qual é o seu nome?")
leia(nome)
escreval("Olá ", nome, ", é um prazer te conhecer!")


Fimalgoritmo