Algoritmo "ex04"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/10/2021
Var
// Seção de Declarações das variáveis 
n1, n2, resul: real


Inicio

escreva("digite um números: ")
leia(n1)
escreva("digite outrp números: ")
leia(n2)
resul <- n1+n2
escreval("A soma entre",n1, " +",n2, " é igual a:", resul)



Fimalgoritmo