Algoritmo "EX06"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/10/2021
Var
// Seção de Declarações das variáveis 
n1,ant,suc: inteiro

Inicio
escreva("digite um número: ")
leia(n1)
ant <- n1 - 1
suc <- n1 + 1
escreval("O antecessor de",n1, " é", ant)
escreval("O sucessor de",n1, " é", suc)
Fimalgoritmo