Algoritmo "EX07"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/10/2021
Var
// Seção de Declarações das variáveis
n1,dobro,terco: real

Inicio
escreva("digite um número: ")
leia(n1)
dobro <- n1 * 2
terco <- n1 / 3
escreval("O dobro de",n1, " é ", dobro:2:2)
escreval("O terço de",n1, " é ", terco)
Fimalgoritmo