Algoritmo "EX09"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/10/2021
Var
reais,dolares: real


Inicio
escreval("Quantos reais você tem na carteira: ")
leia(reais)

dolares <-reais / 3.45
escreva("Com R$",reais, " Você pode comprar : U$", dolares)



Fimalgoritmo