Algoritmo "dobroeterço"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2021
Var
// Seção de Declarações das variáveis 
dobro,terca, n: real

Inicio
escreva("Digite um número: ")
leia(n)
dobro <- n * 2
terca <- n / 3
escreval   ("O dobro de", n, " é:", dobro)
escreva("o terço é: ", terca)

Fimalgoritmo