Algoritmo "qual seu nome?"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2021
Var
// Seção de Declarações das variáveis 
nome: caractere

Inicio
escreva("qual o seu nome? ")
leia(nome)
escreva("Olá ", nome, ", é um prazer te conhecer!")

Fimalgoritmo