Algoritmo "somatório entre 2 números"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2021
Var
n1,n2: inteiro
soma: real

Inicio
escreval("Digite um número? ")
leia(n1)
escreval("digite outro número? ")
leia(n2)
soma <- n1 + n2
escreva("A soma entre", n1, " +", n2, " é:", soma)


Fimalgoritmo